### ISSUE TITLE
Translation to English

### ISSUE THREAD

**Issue by gurugio** [gurugio/book_assembly_8086#1]
Please write any feedback here.

**Comment by chouoo** [comment]
kldp.org에서 보고 몇가지 코멘트 드립니다.


컴퓨터 세계의 태초에 말씀이 있었으니 어셈블리 언어입니다.

In the Beginning of the computer world, there is a Word. It's the Assembly language.
프로그래밍 언어라기에는 너무 컴퓨터에 가까워서 언어라고 하기 어렵고
 그렇다고 0과 1로 이루어진 컴퓨터 신호도 아닌 이상한 언어입니다.

It's so close to the machine that it's hard to call it a language. But it's neither binary code with 0 and 1.
==> (제안) It's so close to the machine, so it's hard to call it a language. It's a weird language as it's not simply binary code as 0 and 1.

태초의 언어이므로 컴퓨터의 세부적인 동작 하나하나를 직접 지시할 수 있습니다.

The assembly exists since the beginning. It can command direcly the command in very detail.
==> (제안) Since assembly language is like a machine language, it is possible to control computer behavior in very specific.

그렇기 어셈블리 언어를 배운다는 것은 프로그래밍을 배운다기보다는
 컴퓨터 그 자체를 배우는 것에 가깝습니다.

Therefore learning the assembly is rather close to learning the computer than programming.
==> (제안) So learning assembly is much like to learn computer itself rather than programming.

그런데 그렇게 컴퓨터 그 자체를 배우다보면 세상 모든 프로그래밍 언어가
 어떤 원리로 돌아가는지 알게됩니다.

If you understand the computer itself you can see deep inside of the all programming languages. And you can see the principle common to all programming languages.
==> (제안) Studying computer itself is very helpful to figure out how all programming language in the world work on a computer.

마치 매트릭스 세계에서 네오가 세상을 코드로 보는 것처럼
 컴퓨터 세상의 모든게 어셈블리 기호들로 보이기 시작합니다.

It's like that Neo can see the code of Matrix. You can see the assembly code of programs.
==> So I guess, you will be able to see all programs as assembly as just like Neo at Matrix movie see the real world as code.

그래서 너무나 재밌습니다.
It's really fun.

복잡한 컴퓨터 세상을 이루는 원리들이 눈에 보인다는 것은 새로운 세상이 열리는것 같지요.

You will meet the new world inside of the computer that is actuall composed by many layers. But you can see the very deep aspect of the computer world.
==> (제안) Learning assembly sounds like visiting new world because it makes you have an ability to understand and handle the complicated computer.

어셈블리 언어를 배우면 프로그래밍을 더 잘하거나 실력이 좋아진다는 말은 못합니다.

I cannot say that you would be super programmer if you know the assembly.
그래도 처음 어셈블리 언어를 배우고 컴퓨터 세상에 대해 새롭게 눈뜬 순간의 흥분은
 아직도 저를 이끌어서 리눅스 커널과 컴퓨터 구조를 공부하게 만들고 있습니다.

But the excitement I felt when I first knew the assembly led me to the another world, Linux kernel and computer architecture.
==> (제안) But, the moment of when I met the computer after learning assembly first time is the driving force time which guides me the study of Linux kernel and computer architecture.

많은 분들이 세상을 다르게 볼 수 있는 기회를 가지셨으면 합니다.

I want more people to have the chance to see the other aspect of the computer world.

I want to be Morpheus who gave the Red Pill to Neo ;-)
==> (제안) I want to be the Morpheus who gave the Red Pill to Neo ;-)

**Comment by gurugio** [comment]
감사합니다. 곧 수정하겠습니다.
