### ISSUE TITLE
ds:[bx] is explained poorly

### ISSUE THREAD

**Issue by fschutt** [gurugio/book_assembly_8086#8]
In https://github.com/gurugio/book_assembly_8086/blob/master/memoryreadwrite.md there is a flaw where you assume that the reader knows what `ds:[bx]` is, but it is never used in the code (which runs fine). Maybe a syntax error? There is no `ds:[bx]` to be found in an example, so it's hard to understand where and why you need it.

> And ds appears again in ``mov ds:[bx], cx``.

It doesn't. There's no `ds:[bx]` in the assembly code, very confusing:

```asm
org 100h
mov ax, 0b800h
mov ds, ax
mov cl, 'A'
mov ch, 11011111b
mov bx, 15eh
mov [bx], cx
ret
```

At the end you say that you switched to `mov [bx], cx` which "does the same", but please don't do this. The whole paragraph is assuming that the code still uses `ds:[bx]`.

**Comment by gurugio** [comment]
I think I explained that every addressing needs segment register.
"mov [bx], cx" is "mov ds:[bx], cx"
"ds:" can be omitted because default segment register is ds.
If you want to use other segment registers, you should write it.
But you can ommit ds.

I'll write more about that.
Thank you to inform me ;-)

**Comment by gurugio** [comment]
You're right.
Yes, example source should be "mov ds:[bx], cx".
It was my mistake.
I changed it.

**Comment by fschutt** [comment]
Alright, thanks.
